const list = [
  { name: "권유담", useYn: "N" },
  { name: "김광은", useYn: "N" },
  { name: "김대원", useYn: "N" },
  { name: "김예림", useYn: "N" },
  { name: "김예송", useYn: "Y" },
  { name: "김여명", useYn: "N" },
  { name: "김지원", useYn: "N" },
  { name: "김지주", useYn: "N" },
  { name: "김찬우", useYn: "N" },
  { name: "김태훈", useYn: "Y" },
  { name: "박도희", useYn: "Y" },
  { name: "박병호", useYn: "N" },
  { name: "박예빈", useYn: "N" },
  { name: "박윤걸", useYn: "Y" },
  { name: "박윤지", useYn: "N" },
  { name: "박인서", useYn: "N" },
  { name: "백민서", useYn: "Y" },
  { name: "백민우", useYn: "N" },
  { name: "백하영", useYn: "N" },
  { name: "서봉규", useYn: "N" },
  { name: "신지원", useYn: "N" },
  { name: "오송현", useYn: "Y" },
  { name: "유리", useYn: "Y" },
  { name: "이명철", useYn: "Y" },
  { name: "이민수", useYn: "Y" },
  { name: "이신우", useYn: "Y" },
  { name: "이연우", useYn: "N" },
  { name: "이유나", useYn: "Y" },
  { name: "이지우", useYn: "Y" },
  { name: "이찬미", useYn: "Y" },
  { name: "장진영", useYn: "N" },
  { name: "전솔담", useYn: "Y" },
  { name: "정다훈", useYn: "N" },
  { name: "주예지", useYn: "N" },
  { name: "차영광", useYn: "N" },
  { name: "최소민", useYn: "Y" },
  { name: "한예지", useYn: "N" },
  { name: "강도사님", useYn: "N" },
  { name: "부장님", useYn: "N" }
];

export default list;
